theme: jekyll-theme-minimal
title: Gustav Karreskog
description: I am a PhD candidate in economics at the Stockholm School of Economics. I am on the academic job market 2020/2021. 
logo: portrait.jpg
google_analytics: UA-179312517-1 
