theme: jekyll-theme-minimal
title: Gustav Karreskog
description: Personal web page for Gustav Karreskog, PhD candidate in economics at the stockholm school of economics. Here you can see my CV and papers.
logo: portrait.jpg
